#pragma once

#include "../SDK.h"

// Name: S3Demo, Version: 0.90.0

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

namespace SDK
{
//---------------------------------------------------------------------------
// Parameters
//---------------------------------------------------------------------------

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.setFreeAnimStartPos
struct UABP_AR_BoxTutle_C_setFreeAnimStartPos_Params
{
	float                                              StartPos;                                                 // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_1C8D52374E1162CC64B26FA0F8D367CD
struct UABP_AR_BoxTutle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_1C8D52374E1162CC64B26FA0F8D367CD_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_2901D1E54E7B618E47ECB4A3D37961A2
struct UABP_AR_BoxTutle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_2901D1E54E7B618E47ECB4A3D37961A2_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_FF9727C848BA4D96D17A7CAA3FEAE8CE
struct UABP_AR_BoxTutle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_FF9727C848BA4D96D17A7CAA3FEAE8CE_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_AABCF64A46E37CA88BAD7FB196B443CA
struct UABP_AR_BoxTutle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_AABCF64A46E37CA88BAD7FB196B443CA_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_7A5E323C4E8F7103074445AECC8E53C4
struct UABP_AR_BoxTutle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_7A5E323C4E8F7103074445AECC8E53C4_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_5D927C924F161B378809159B66E48E16
struct UABP_AR_BoxTutle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_5D927C924F161B378809159B66E48E16_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_F6C047BB4D22C635DC4F62AD8A163379
struct UABP_AR_BoxTutle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_F6C047BB4D22C635DC4F62AD8A163379_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_7D9B06D34CD3CE9330064BB7D890234E
struct UABP_AR_BoxTutle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_7D9B06D34CD3CE9330064BB7D890234E_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_CF32E80848009C24A9099093ACF6D16E
struct UABP_AR_BoxTutle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_CF32E80848009C24A9099093ACF6D16E_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_ED4CBEC44A5D9A02762FD29EAD61EDFB
struct UABP_AR_BoxTutle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_ED4CBEC44A5D9A02762FD29EAD61EDFB_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_D38462BC47E3D2F5084160A7BEFE6D4A
struct UABP_AR_BoxTutle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_D38462BC47E3D2F5084160A7BEFE6D4A_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_9BA18C32463B596CFAF0E29EC761E56E
struct UABP_AR_BoxTutle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_9BA18C32463B596CFAF0E29EC761E56E_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_D8E9A4264FA2B8B62D0F81A5B771ADD0
struct UABP_AR_BoxTutle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_D8E9A4264FA2B8B62D0F81A5B771ADD0_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_C95C73B442B837563C247EA57E367503
struct UABP_AR_BoxTutle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_C95C73B442B837563C247EA57E367503_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_91D7F7BC4514EF9B05157891446308EC
struct UABP_AR_BoxTutle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_91D7F7BC4514EF9B05157891446308EC_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_B98D9A17485BB480A67626A615DEFC94
struct UABP_AR_BoxTutle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_B98D9A17485BB480A67626A615DEFC94_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_B29477B5467D0FE74AAB26A64E822E58
struct UABP_AR_BoxTutle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_B29477B5467D0FE74AAB26A64E822E58_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_296B3CB445EFACF49DBFB19CC077AB39
struct UABP_AR_BoxTutle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_296B3CB445EFACF49DBFB19CC077AB39_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_SequencePlayer_6C2D75B647B7651CA13C35A5F0AAF4FA
struct UABP_AR_BoxTutle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_SequencePlayer_6C2D75B647B7651CA13C35A5F0AAF4FA_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_A69BBB404B758D552F109796B1D2B50E
struct UABP_AR_BoxTutle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_A69BBB404B758D552F109796B1D2B50E_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_BlendSpacePlayer_6234766F49F8A4D46AB1CD86339BBF1D
struct UABP_AR_BoxTutle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_BlendSpacePlayer_6234766F49F8A4D46AB1CD86339BBF1D_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_C19F25DB42A88D065E0F72A61C77F559
struct UABP_AR_BoxTutle_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_AR_BoxTutle_AnimGraphNode_TransitionResult_C19F25DB42A88D065E0F72A61C77F559_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.AnimNotify_BoxturtleDeath_Anim_Finished
struct UABP_AR_BoxTutle_C_AnimNotify_BoxturtleDeath_Anim_Finished_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.AnimNotify_MG_AnimalCry
struct UABP_AR_BoxTutle_C_AnimNotify_MG_AnimalCry_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.AnimNotify_MG_WalkTiming
struct UABP_AR_BoxTutle_C_AnimNotify_MG_WalkTiming_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.ExecuteUbergraph_ABP_AR_BoxTutle
struct UABP_AR_BoxTutle_C_ExecuteUbergraph_ABP_AR_BoxTutle_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.Anim_WalkTiming__DelegateSignature
struct UABP_AR_BoxTutle_C_Anim_WalkTiming__DelegateSignature_Params
{
};

// Function ABP_AR_BoxTutle.ABP_AR_BoxTutle_C.Anim_CryTiming__DelegateSignature
struct UABP_AR_BoxTutle_C_Anim_CryTiming__DelegateSignature_Params
{
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
